name: spreadit_crossplatform
description: "Reddit recreated, but cooler."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  ionicons: ^0.2.2

  flutter_bloc: ^8.1.2

  equatable: ^2.0.5

  get_it: ^7.6.0
  
  intl: ^0.19.0
  
  retrofit: ^4.1.0

  flutter_hooks: ^0.20.5

  cached_network_image: ^3.2.0
  
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  retrofit_generator: ^8.1.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.8
  

flutter:

  uses-material-design: true